package com.sunofbeaches.recyclervie

object requestData {
    val resultJson = "{\n" +
            "\"code\":200,\n" +
            "\"message\":\"ok\",\n" +
            "\"data\":[\n" +
            "{\n" +
            "\"title\":\"WebStorm破解版下载\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/25/rBsADV8ShY-AZHzMAACdlFkX4V0413.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"请求地址和数据拼接都没问题，运行到post方法时错误\",\n" +
            "\"covers\":[],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"Sqlite数据库测试遍历异常\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/27/rBsADV8e9xOAb3CJAACF8-fpOjs693.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/26/rBsADV8aV3-AcgEtAAP5acyoQx4267.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2B/rBsADV83ZnuAT6JuAABSrMRZz_U253.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"绘图软件分享--Draw.io\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9EjmWAG_-qAABuaMiqXIQ189.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于tablayout使用中的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzomAdfC4AABXZaXo98g234.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/21/rBsADV7bZxKARCnnAAD6ZlAS6Q4312.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"在编写了checkUser过后,启动springboot就会报错\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7skRmAJmvIAACGYg4SVPE188.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于RecyclerView点击删除后 页面就没响应的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/23/rBsADV72DTmAawRnAAASQ7bNI0E949.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"搭建hadoop集群笔记\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV81Al-AJjttAAC04It1XrM326.jpg\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8uXzyAIyT_AACVeyj__OU027.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8xV8eAS4VwAACnccnFNCg149.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"PhpStorm破解版下载\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV8zpKuAJ-fSAAKYQ9XrYYY571.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"请求地址和数据拼接都没问题，运行到post方法时错误\",\n" +
            "\"covers\":[],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"Sqlite数据库测试遍历异常\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/27/rBsADV8e9xOAb3CJAACF8-fpOjs693.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/26/rBsADV8aVwyAQGV5AAApIXZDWcM990.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2B/rBsADV83ZnuAT6JuAABSrMRZz_U253.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},\n" +
            "{\n" +
            "\"title\":\"绘图软件分享--Draw.io\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9EjmWAG_-qAABuaMiqXIQ189.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于tablayout使用中的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzomAdfC4AABXZaXo98g234.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/21/rBsADV7bZxKARCnnAAD6ZlAS6Q4312.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"在编写了checkUser过后,启动springboot就会报错\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzpyASDj3AAE2twD_75k116.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于RecyclerView点击删除后 页面就没响应的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/23/rBsADV72DTmAawRnAAASQ7bNI0E949.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"搭建hadoop集群笔记\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV81Al-AJjttAAC04It1XrM326.jpg\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8uXzyAIyT_AACVeyj__OU027.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8xV8eAS4VwAACnccnFNCg149.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "}\n" +
            ",\n" +
            "{\n" +
            "\"title\":\"绘图软件分享--Draw.io\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9EjmWAG_-qAABuaMiqXIQ189.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于tablayout使用中的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzomAdfC4AABXZaXo98g234.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/21/rBsADV7bZxKARCnnAAD6ZlAS6Q4312.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"在编写了checkUser过后,启动springboot就会报错\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzpyASDj3AAE2twD_75k116.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于RecyclerView点击删除后 页面就没响应的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/23/rBsADV72DTmAawRnAAASQ7bNI0E949.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"搭建hadoop集群笔记\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV81Al-AJjttAAC04It1XrM326.jpg\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8uXzyAIyT_AACVeyj__OU027.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8xV8eAS4VwAACnccnFNCg149.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "}\n" +
            ",\n" +
            "{\n" +
            "\"title\":\"绘图软件分享--Draw.io\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9EjmWAG_-qAABuaMiqXIQ189.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于tablayout使用中的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzomAdfC4AABXZaXo98g234.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/21/rBsADV7bZxKARCnnAAD6ZlAS6Q4312.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"在编写了checkUser过后,启动springboot就会报错\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzpyASDj3AAE2twD_75k116.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于RecyclerView点击删除后 页面就没响应的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/23/rBsADV72DTmAawRnAAASQ7bNI0E949.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"搭建hadoop集群笔记\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV81Al-AJjttAAC04It1XrM326.jpg\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8uXzyAIyT_AACVeyj__OU027.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8xV8eAS4VwAACnccnFNCg149.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "}\n" +
            ",\n" +
            "{\n" +
            "\"title\":\"绘图软件分享--Draw.io\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9EjmWAG_-qAABuaMiqXIQ189.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于tablayout使用中的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzomAdfC4AABXZaXo98g234.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/21/rBsADV7bZxKARCnnAAD6ZlAS6Q4312.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"在编写了checkUser过后,启动springboot就会报错\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/22/rBsADV7uzpyASDj3AAE2twD_75k116.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"关于RecyclerView点击删除后 页面就没响应的问题\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/23/rBsADV72DTmAawRnAAASQ7bNI0E949.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/2E/rBsADV9G_1uAddfGAARh3p4Kjnw827.jpg\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "},{\n" +
            "\"title\":\"搭建hadoop集群笔记\",\n" +
            "\"covers\":[\"https://imgs.sunofbeaches.com/group1/M00/00/2A/rBsADV81Al-AJjttAAC04It1XrM326.jpg\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8uXzyAIyT_AACVeyj__OU027.png\",\"https://imgs.sunofbeaches.com/group1/M00/00/29/rBsADV8xV8eAS4VwAACnccnFNCg149.png\"],\n" +
            "\"viewCount\":10,\n" +
            "\"commentCount\":30\n" +
            "}\n" +
            "]\n" +
            "}\n"
}